# -*- coding: utf-8 -*-
"""
/***************************************************************************
 SelectMatchingFeatures
                                 A QGIS plugin
 Clicking a feature will select all features in layer with same attribute value
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-01-29
        copyright            : (C) 2022 by Matt
        email                : m_needle@hotmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load SelectMatchingFeatures class from file SelectMatchingFeatures.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .select_matching_features import SelectMatchingFeatures
    return SelectMatchingFeatures(iface)
